name: bash-test-if-else

on:
  push:
  pull_request:

jobs:
  test-if-else:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Marcar .sh como ejecutables
        run: |
          find scripts -type f -name '*.sh' -print0 | xargs -0 chmod +x

      - name: Ejecutar solo test_01_if_else.sh
        run: |
          set -e
          echo "Ejecutando scripts/tests/02_flow_control/test_01_if_else.sh ..."
          bash scripts/tests/02_flow_control/test_01_if_else.sh > scripts/tests/02_flow_control/test_01_if_else.log 2>&1
          echo "test_01_if_else.sh OK"
